### ISSUE TITLE
Support for "state" dates

### ISSUE THREAD

**Issue by syphernl** [gadgetchnnel/entities_calendar#1]
The [ROVA trash](https://www.home-assistant.io/integrations/rova/) integration doesn't use `last_changed` but puts the date in the state instead. 

It would be nice if this integration could support that as well, right now it's throwing exceptions because the entity doesn't contain a date/`last_changed` field:

```
2020-05-29 13:41:54 ERROR (MainThread) [homeassistant.helpers.entity] Update for calendar.trash fails
Traceback (most recent call last):
  File "/srv/hass/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/srv/hass/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 472, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/hass/.homeassistant/custom_components/entities_calendar/calendar.py", line 111, in update
    self.data.update()
  File "/srv/hass/lib/python3.8/site-packages/homeassistant/util/__init__.py", line 239, in wrapper
    result = method(*args, **kwargs)
  File "/home/hass/.homeassistant/custom_components/entities_calendar/calendar.py", line 195, in update
    "date": start.strftime('%Y-%m-%d'),
AttributeError: 'NoneType' object has no attribute 'strftime'
```

**Comment by gadgetchnnel** [comment]
It will pick up the date from the state, but only if the device_class is "timestamp". You should be able to override this in HA using **customize** (either through the UI or YAML):

https://www.home-assistant.io/docs/configuration/customizing-devices/

**Comment by syphernl** [comment]
Thanks for your quick reply :) I have changed the 3 items the ROVA integration creates to `device_class: timestamp` but no luck. Could that be because one of the entities is currently showing `state: unknown`?

**Comment by gadgetchnnel** [comment]
I have just pushed a new release (0.0.3) which filters out "timestamp" entities with an "unknown" or "unavailable" state. Can you try updating to that version and see if it works?

**Comment by syphernl** [comment]
> I have just pushed a new release (0.0.3) which filters out "timestamp" entities with an "unknown" or "unavailable" state. Can you try updating to that version and see if it works?

Works like a charm!

**Comment by gadgetchnnel** [comment]
I may add an option at some point that allows you to use the state of any entity without changing the device class to "timestamp" (e.g. an option like `use_state: true` under the entity) as there may be reasons why you wouldn't want to change the device class.
