### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'strftime'

### ISSUE THREAD

**Issue by syphernl** [gadgetchnnel/entities_calendar#3]
The issue of #1 `AttributeError: 'NoneType' object has no attribute 'strftime'` is coming by pretty frequently in my logs (running HASS `0.110.7` or `0.111.0`). 

Full traceback:
```
2020-06-10 17:37:35 ERROR (MainThread) [homeassistant.helpers.entity] Update for calendar.trash fails
Traceback (most recent call last):
  File "/srv/hass/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/srv/hass/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 472, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/hass/.homeassistant/custom_components/entities_calendar/calendar.py", line 168, in update
    self.data.update()
  File "/srv/hass/lib/python3.8/site-packages/homeassistant/util/__init__.py", line 239, in wrapper
    result = method(*args, **kwargs)
  File "/home/hass/.homeassistant/custom_components/entities_calendar/calendar.py", line 251, in update
    "date": start.strftime('%Y-%m-%d'),
AttributeError: 'NoneType' object has no attribute 'strftime'
```

Perhaps a check could be added to see if `start` is not None before trying to apply strftime on it to prevent this from clogging up the logs.

**Comment by gadgetchnnel** [comment]
Can you please try this with the new release, 0.0.5, which should have improved checking for missing entities, states, and attributes?

**Comment by syphernl** [comment]
Works like a charm!
